"""FAISS searcher backed by a configurable embedding provider."""

from __future__ import annotations

import glob
import json
import logging
import os
import pickle
from typing import Any, Optional

import faiss
import numpy as np
from datasets import load_dataset
from tqdm import tqdm

from embedding_client import create_embedding_client

from .base import BaseSearcher

logger = logging.getLogger(__name__)


class ConfigurableFaissSearcher(BaseSearcher):
    @classmethod
    def parse_args(cls, parser):
        parser.add_argument(
            "--index-path",
            required=True,
            help="Glob pattern for dense pickle shards, e.g. /path/to/corpus.*.pkl.",
        )
        parser.add_argument(
            "--embedding-config-json",
            required=True,
            help="JSON object with embedding provider settings.",
        )
        parser.add_argument(
            "--index-metadata",
            help="Optional metadata.json generated by build_dense_index.py.",
        )
        parser.add_argument(
            "--metric",
            choices=["inner_product", "l2"],
            default="inner_product",
            help="FAISS metric to use for search. Must match how the index was built.",
        )
        parser.add_argument(
            "--dataset-name",
            default="Tevatron/browsecomp-plus-corpus",
            help="Dataset name for document text lookup.",
        )
        parser.add_argument(
            "--dataset-split",
            default="train",
            help="Dataset split for document text lookup.",
        )
        parser.add_argument(
            "--corpus-file",
            help="Optional local JSONL corpus for document text lookup.",
        )
        parser.add_argument(
            "--docid-field",
            default="docid",
            help="Corpus field containing document IDs.",
        )
        parser.add_argument(
            "--text-field",
            default="text",
            help="Corpus field containing document text.",
        )

    def __init__(self, args):
        if not args.index_path:
            raise ValueError("index_path is required for configurable FAISS searcher")

        self.args = args
        self.embedding_config = json.loads(args.embedding_config_json)
        self.embedding_client = create_embedding_client(self.embedding_config)
        self.index: faiss.Index | None = None
        self.lookup: list[str] = []
        self.docid_to_text: dict[str, str] = {}
        self.dimension: int | None = None
        self.metadata: dict[str, Any] = {}

        logger.info("Initializing configurable FAISS searcher...")
        self._load_metadata()
        self._load_faiss_index()
        self._load_documents()
        logger.info("Configurable FAISS searcher initialized successfully")

    def _load_metadata(self) -> None:
        if not self.args.index_metadata:
            return
        if not os.path.exists(self.args.index_metadata):
            logger.warning("Index metadata not found: %s", self.args.index_metadata)
            return
        with open(self.args.index_metadata, encoding="utf-8") as f:
            self.metadata = json.load(f)

        metadata_metric = self.metadata.get("metric")
        if metadata_metric and metadata_metric != self.args.metric:
            logger.warning(
                "Configured metric %s differs from metadata metric %s",
                self.args.metric,
                metadata_metric,
            )

    def _new_index(self, dimension: int) -> faiss.Index:
        if self.args.metric == "l2":
            return faiss.IndexFlatL2(dimension)
        return faiss.IndexFlatIP(dimension)

    def _load_faiss_index(self) -> None:
        index_files = sorted(glob.glob(self.args.index_path))
        logger.info("Pattern match found %s files; loading them into FAISS.", len(index_files))
        if not index_files:
            raise ValueError(f"No files found matching pattern: {self.args.index_path}")

        for path in tqdm(index_files, desc="Loading dense shards"):
            with open(path, "rb") as f:
                reps, lookup = pickle.load(f)
            arr = np.asarray(reps, dtype="float32")
            if arr.ndim != 2:
                raise ValueError(f"Index shard {path} must contain a 2D array, got shape {arr.shape}")

            if self.index is None:
                self.dimension = int(arr.shape[1])
                self.index = self._new_index(self.dimension)
            elif arr.shape[1] != self.dimension:
                raise ValueError(
                    f"Index shard {path} has dimension {arr.shape[1]}, expected {self.dimension}"
                )

            if len(lookup) != arr.shape[0]:
                raise ValueError(f"Index shard {path} has {arr.shape[0]} vectors but {len(lookup)} lookup IDs")

            self.index.add(np.ascontiguousarray(arr))
            self.lookup.extend(str(docid) for docid in lookup)

        expected_dim = self.metadata.get("dimension")
        if expected_dim and self.dimension and int(expected_dim) != self.dimension:
            logger.warning("Metadata dimension %s differs from loaded dimension %s", expected_dim, self.dimension)

    def _load_documents(self) -> None:
        docid_field = self.args.docid_field
        text_field = self.args.text_field

        if self.args.corpus_file:
            logger.info("Loading local corpus file: %s", self.args.corpus_file)
            with open(self.args.corpus_file, encoding="utf-8") as f:
                for i, line in enumerate(f):
                    if not line.strip():
                        continue
                    row = json.loads(line)
                    docid = str(row.get(docid_field, i))
                    self.docid_to_text[docid] = str(row.get(text_field, ""))
            return

        logger.info("Loading dataset: %s split=%s", self.args.dataset_name, self.args.dataset_split)
        dataset_cache = os.getenv("HF_DATASETS_CACHE") or None
        ds = load_dataset(self.args.dataset_name, split=self.args.dataset_split, cache_dir=dataset_cache)
        self.docid_to_text = {
            str(row.get(docid_field, i)): str(row.get(text_field, ""))
            for i, row in enumerate(ds)
        }
        logger.info("Loaded %s passages for text lookup", len(self.docid_to_text))

    def search(self, query: str, k: int = 10) -> list[dict[str, Any]]:
        if self.index is None or self.dimension is None or not self.lookup:
            raise RuntimeError("Searcher not properly initialized")

        q_vec = np.asarray([self.embedding_client.embed_query(query)], dtype="float32")
        if q_vec.shape[1] != self.dimension:
            raise ValueError(
                f"Query embedding dimension {q_vec.shape[1]} does not match index dimension {self.dimension}"
            )

        scores, indices = self.index.search(np.ascontiguousarray(q_vec), k)
        results: list[dict[str, Any]] = []
        for score, index in zip(scores[0], indices[0]):
            if index < 0:
                continue
            passage_id = self.lookup[int(index)]
            passage_text = self.docid_to_text.get(passage_id, "Text not found")
            results.append({"docid": passage_id, "score": float(score), "text": passage_text})
        return results

    def get_document(self, docid: str) -> Optional[dict[str, Any]]:
        text = self.docid_to_text.get(str(docid))
        if text is None:
            return None
        return {"docid": str(docid), "text": text}

    @property
    def search_type(self) -> str:
        return "configurable_faiss"
